export const productsName = [
  {
    id: "1",
    ru: "картофель",
    en: "potato",
    imgUrl: "/img/potato.jpg",
    typeId: "1",
  },
  {
    id: "2",
    ru: "помидор",
    en: "tomato",
    imgUrl: "/img/tomato.png",
    typeId: "1",
  },
  {
    id: "3",
    ru: "огурец",
    en: "cucumber",
    imgUrl: "/img/cucumber.jpeg",
    typeId: "1",
  },
  {
    id: "4",
    ru: "морковь",
    en: "carrot",
    imgUrl: "/img/carrot.jpeg",
    typeId: "1",
  },
  { id: "5", ru: "лук", en: "onion", imgUrl: "/img/onion.jpeg", typeId: "1" },
  {
    id: "6",
    ru: "тыква",
    en: "pumpkin",
    imgUrl: "/img/pumpkin.webp",
    typeId: "1",
  },
  {
    id: "7",
    ru: "молоко",
    en: "milk",
    imgUrl: "/img/milk.jpeg",
    typeId: "2",
  },
  {
    id: "8",
    ru: "говядина",
    en: "cow-meet",
    imgUrl: "/img/cow-meet.webp",
    typeId: "3",
  },
  {
    id: "9",
    ru: "банан",
    en: "banana",
    imgUrl: "/img/banana.jpeg",
    typeId: "4",
  },
];
